#!/usr/bin/env bash
# credit: @chrstphr
# $1 is local directory path
# $2 is git branch to create diff against
# $3 is ssh remote host
# $4 is remote directory path

LOCAL_DIR="${1:?"Local directory not specified!"}"
GIT_BRANCH="${2:?"Branch to compare with not specified"}"
REMOTE_HOST="${3:?"Remote host not specified!"}"
REMOTE_DIR="${4:?"Remote directory not specified!"}"


# git apply --index adds files that are untracked into the index, such that on
# the next git reset, this file will be deleted. Therefore, there will be no
# conflicts with untracked files
git -C "$LOCAL_DIR" diff "$GIT_BRANCH" | ssh "$REMOTE_HOST" " git -C '$REMOTE_DIR' reset --hard '$GIT_BRANCH' && git -C '$REMOTE_DIR' apply --index --whitespace=nowarn - "

