#!/usr/bin/env bash
# credit: chrstphr
# $1 is local directory path
# $2 is ssh remote host
# $3 is remote directory path

LOCAL_DIR="${1:?"Local directory not specified!"}"
REMOTE_HOST="${2:?"Remote host not specified!"}"
REMOTE_DIR="${3:?"Remote directory not specified!"}"

GIT_BRANCH=$(git -C "$LOCAL_DIR" rev-parse --abbrev-ref HEAD)

# git apply --index adds files that are untracked into the index, such that on
# the next git reset, this file will be deleted. Therefore, there will be no
# conflicts with untracked files
git -C "$LOCAL_DIR" diff origin/"$GIT_BRANCH" | ssh "$REMOTE_HOST" " git -C '$REMOTE_DIR' fetch origin && git -C '$REMOTE_DIR' reset --hard origin/'$GIT_BRANCH' && git -C '$REMOTE_DIR' apply --index --whitespace=nowarn - "

