#!/usr/bin/env bash
echo Starting uncommitted-changes-sync
# trap to kill processes that we start in this script when this script finishes
trap "kill 0" EXIT

# loop over lines in config file
# the sed command removes lines starting with "#" or empty lines
sed -e "/^#\\|^\$/d" < config | while read localpath_unexpanded host remotepath; do
    # in case there's something like $HOME in the localpath, evaluate it 
    eval localpath=$localpath_unexpanded

    echo
    echo Location
    echo "  local path:  $localpath"
    echo "  host:        $host"
    echo "  remote path: $remotepath"

    ./inotifydo ./git_upd $localpath $host $remotepath &
done;

echo " "
echo "Done setting up syncers."
echo " "

# This is elegant, I know!
sleep infinity
